package com.ecommerce.backend;

import com.ecommerce.backend.model.Scarpa;
import com.ecommerce.backend.repository.ScarpaRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

@Component // Annotazione che fa eseguire la classe all'avvio
public class DatabaseLoader implements CommandLineRunner {

    private final ScarpaRepository repo;

    public DatabaseLoader(ScarpaRepository repo) {
        this.repo = repo;
    }

    @Override
    public void run(String... args) throws Exception {
        // Controllo se il DB è vuoto per non duplicare i dati ad ogni riavvio
        if (repo.count() == 0) {
            System.out.println("🚚 Inizio caricamento database scarpe...");
            repo.save(Scarpa.builder().nome("Adidas Yeezy Boost 350 V2 nero lucido").prezzo(229.99d).descrizione("le Adidas Yeezy 350 V2 ritornano alle origini, utilizzando colori leggeri per enfatizzare la complessità della sua costruzione. Il motivo a righe laterali in mesh e il passante sul tallone in tela creano un delicato contrasto di materiali").marchio("Adidas").modello("Yeezy Boost 350 V2").tagliaDisponibile(44).imageUrl("ADYB350V2Black.png").build());
            repo.save(Scarpa.builder().nome("Adidas Campus 80s Sout Park Towelie").prezzo(179.99d).descrizione("Adidas con questa versione fa riferimento a Towelie, un personaggio di South Park, le scarpe resentano una tomaia in spugna viola con sovrapposizioni in pelle bianca e fodera in pelle viola").marchio("Adidas").modello("Campus 80s").tagliaDisponibile(44).imageUrl("ADC80.png").build());
            repo.save(Scarpa.builder().nome("Adidas Campus 00s blu semilucido bianco nuvola").prezzo(94.99d).descrizione("Adidas con questa scarpa si ispira agli anni 2000, con una tomaie in pelle scamosciata di prima qualità,  con le classiche strisce Adidas in Cloud White. L'intersuola bianca e la suola Lucid Blue completano questa colorway visivamente accattivante").marchio("Adidas").modello("Campus 00s").tagliaDisponibile(43).imageUrl("ADC00sBlue.png").build());
            repo.save(Scarpa.builder().nome("Adidas Campus 00s nere").prezzo(89.99d).descrizione("Le Adidas Campus 00s Core Black sono rivestite da colorazioni bianche e nere sulla tomaia, intersuola bianca e suola marrone. Queste sneaker sono realizzate con materiali in pelle scamosciata, gomma e cuoio che ne completano la struttura.").marchio("Adidas").modello("Campus 00s").tagliaDisponibile(36).imageUrl("ADC00sBlack.png").build());
            repo.save(Scarpa.builder().nome("Adidas Campus 2 KoRn Follow The Leader").prezzo(159.99d).descrizione("le Campus 00s tendono a calzare fedelmente alla taglia, realizzate con una tomaia in pelle premium rivestita in morbido tessuto di spugna, il tutto su un'intersuola bianco sporco: un chiaro collegamento con l'eredità del Campus.").marchio("Adidas").modello("Campus 2").tagliaDisponibile(37).imageUrl("ADC2.png").build());
            repo.save(Scarpa.builder().nome("Adidas Samba OG cartone").prezzo(129.99d).descrizione("Le Adidas Samba Cardboard sono una delle varianti più apprezzate della famiglia Samba. Con il loro colore ispirato al cartone, queste scarpe si distinguono per la loro capacità di fondersi con un'ampia gamma di colori e tessuti,").marchio("Adidas").modello("Samba OG").tagliaDisponibile(39).imageUrl("ADSOG.png").build());
            repo.save(Scarpa.builder().nome("Adidas Yeezy Boost 350 V2 bianco sporco").prezzo(259.99d).descrizione("Il modello è principalmente bianco e mantiene questa caratteristica monocromatica su tutta la silhouette, che mette in risalto i filati a contrasto. La suola massiccia è leggermente ingiallita, e la fascia spessa che corre al centro della tomaia in Primeknit aggiunge un altro dettaglio a contrasto e completa il design.").marchio("Adidas").modello("Yeezy Boost 350 V2").tagliaDisponibile(43).imageUrl("ADYB350V2White.png").build());
            repo.save(Scarpa.builder().nome("Adidas Yeezy Boost 350 V2 nero rosso").prezzo(229.99d).descrizione("Le adidas Yeezy Boost 350 V2 nero rosso sono una delle prime colorway originali rilasciate dopo il debutto della silouhette nel 2016. La tomaia è realizzata in materiale nero Primeknit per una maggiore traspirabilità. L'intersuola a coste nera contiene il sistema di ammortizzazione BOOST per un maggiore comfort.").marchio("Adidas").modello("Yeezy Boost 350 V2").tagliaDisponibile(40).imageUrl("ADYB350V2Red.png").build());
            repo.save(Scarpa.builder().nome("Adidas Yeezy Boost 350 V2 grigio beluca").prezzo(219.99d).descrizione("Le YEEZY BOOST 350 V2 Carbon Beluga presentano una tomaia Primeknit bicolore. L'intersuola offre un incredibile ritorno di energia, mentre la gabbia semitrasparente in TPU aggiunge un tocco di stile extra. Sono realizzate utilizzando una serie di materiali riciclati.").marchio("Adidas").modello("Yeezy Boost 350 V2").tagliaDisponibile(45).imageUrl("ADYB350V2Beluca.png").build());
            repo.save(Scarpa.builder().nome("Adidas Yeezy Boost 350 V2 zebra").prezzo(289.99d).descrizione("Adidas torna alle origini con le ultimissime Yeezy Boost 350 V2. Direttamente dall'NBA All-Star Weekend, queste Yeezy sono note come le Zebra, e disponibili nella colorway classica di bianco, nero e rosso. Caratterizzate da una tomaia in Primeknit bianca, hanno inserti neri che ricreano l'effetto zebrato, la scritta SPLY-350 ").marchio("Adidas").modello("Yeezy Boost 350 V2").tagliaDisponibile(39).imageUrl("ADYB350V2Zebra.png").build());
            repo.save(Scarpa.builder().nome("Jordan 1 Retro High OG Chicago Lost and Found").prezzo(239.99d).descrizione("La colorway originale delle Air Jordan 1 Chicago è stata introdotta per la prima volta nel 1985 e da allora è stata riproposta solo poche volte. Gli accenti pre-ingialliti e le tomaie in pelle screpolata servono a creare un look come se le scarpe fossero usate e consumate").marchio("Jordan").modello("Jordan 1 retro high OG").tagliaDisponibile(36).imageUrl("JD1RHOGL.png").build());
            repo.save(Scarpa.builder().nome("Jordan 1 Retro High OG university blue").prezzo(319.99d).descrizione("Jordan rende omaggio all'alma mater di Michael Jordan con queste Air Jordan 1 High University Blue. La colorway University Blue fa da protagonista nella storia delle Jordan 1. La prima versione Jordan 1 UNC risale al 1985, quando le Jordan 1 hanno fatto il loro debutto. ").marchio("Jordan").modello("Jordan 1 retro high OG").tagliaDisponibile(40).imageUrl("JD1RHOGUBlue.png").build());
            repo.save(Scarpa.builder().nome("Jordan 1 Retro High Dark Mocha").prezzo(369.99d).descrizione("Jordan Brand ha ripreso il tema di fondo delle Black Toe nel 2020 con la release delle Jordan 1 High marrone scuro. Il modello marrone scuro è stato uno dei più attesi del 2020").marchio("Jordan").modello("Jordan 1 retro high ").tagliaDisponibile(39).imageUrl("JD1RHDM.png").build());
            repo.save(Scarpa.builder().nome("Jordan 4 Retro nero militare").prezzo(419.99d).descrizione("La Jordan Brand ha cambiato uno dei colori originali Air Jordan 4 per le Air Jordan 4 Military Black, hanno una tomaia in pelle bianca liscia con una punta in Durabuck grigio chiaro e inserti in TPU a rete.").marchio("Jordan").modello("Jordan 4 Retro").tagliaDisponibile(39).imageUrl("JR4RNM.png").build());
            repo.save(Scarpa.builder().nome("Jordan 4 Retro Blu Universitario").prezzo(469.99d).descrizione("Jordan rende omaggio all'alma mater di Michael Jordan con queste Air Jordan 4 University Blue. La colorway University Blue è molto simile al modello Air Jordan 4 UNC PE, estremamente raro, creato per gli studenti-atleti della Tarheel nel 2019.").marchio("Jordan").modello("Jordan 4 Retro").tagliaDisponibile(36).imageUrl("JR4RBU.png").build());
            repo.save(Scarpa.builder().nome("Jordan 4 Retro Blu Militare").prezzo(489.99d).descrizione("Le Air Jordan 4 Retro blu militare 2024 sono un faro dell'innovazione e dello stile del marchio Jordan . Sfoggiano una base in pelle avorio in contrasto con il sorprendente blu militare sugli occhielli, sul tallone e su parti dell'intersuola, creando un look dal design disciplinato ma audace. ").marchio("Jordan").modello("Jordan 4 Retro").tagliaDisponibile(39).imageUrl("JR4RBN.png").build());
            repo.save(Scarpa.builder().nome("Jordan 11 Retro Concord").prezzo(419.99d).descrizione("Jordan Brand ha provato a conquistare il titolo di sneaker dell'anno con il lancio delle Jordan 11 Retro Concord (2018). Questa colorway iconica delle Jordan 11 presenta una tomaia bianca con accenti neri, un'intersuola bianca e una suola traslucida e fredda. ").marchio("Jordan").modello("Jordan 11 Retro").tagliaDisponibile(39).imageUrl("JR11RC.png").build());
            repo.save(Scarpa.builder().nome("Jordan 11 Retro Playoffs rosso nero").prezzo(329.99d).descrizione("Queste Jordan 11 presentano una tomaia nera con sovrapposizioni in vernice lucida e dettagli rossi. La suola traslucida rossa, l'intersuola bianca e il numero 23 sul tallone completano il design").marchio("Jordan").modello("Jordan 11 Retro").tagliaDisponibile(40).imageUrl("JR11RPRN.png").build());
            repo.save(Scarpa.builder().nome("Jordan 11 Retro Jubilee 25th Anniversary").prezzo(269.99d).descrizione("Nel 2020 il brand Jordan festeggia il 25° anniversario della nascita di uno dei suoi modelli più famosi: le Jordan 11. Per commemorare la famosa silhouette, Michael Jordan e Nike presentano le Jordan 11 Jubilee").marchio("Jordan").modello("Jordan 11 Retro").tagliaDisponibile(38).imageUrl("JR11RJ25.png").build());
            repo.save(Scarpa.builder().nome("Jordan 4 Retro blu notte").prezzo(329.99d).descrizione("Air Jordan 4 Retro Midnight Navy, realizzata in pelle premium. L'iconica rete in rete di plastica sui lati e gli occhielli in plastica sono di colore blu notte. La sneaker presenta una suola in gomma bianca con accenti blu notte e grigio con spruzzi di colore. Logo Jordan sul tallone e sulla linguetta della scarpa.").marchio("Jordan").modello("Jordan 4 Retro").tagliaDisponibile(39).imageUrl("JR4RBN.png").build());
            repo.save(Scarpa.builder().nome("Nike Air Force 1 Low pianta Cactus mercato delle pulci bianco").prezzo(299.99d).descrizione("Nike Air Force 1 Low pianta Cactus mercato delle pulci sono fatte di un materiale di gomma, pelle e il rivestimento interno è in tessuto.").marchio("Nike").modello("Nike Air Force 1").tagliaDisponibile(36).imageUrl("NKAF1LPCWhite.png").build());
            repo.save(Scarpa.builder().nome("Nike Air Force 1 Low pianta Cactus mercato delle pulci nero").prezzo(269.99d).descrizione("Nike Air Force 1 Low pianta Cactus mercato delle pulci sono fatte di un materiale di gomma, pelle e il rivestimento interno è in tessuto.").marchio("Nike").modello("Nike Air Force 1").tagliaDisponibile(40).imageUrl("NKAF1LDark.png").build());
            repo.save(Scarpa.builder().nome("Nike Air Force 1 Low SP Supreme marrone").prezzo(249.99d).descrizione("Le Nike Air Force 1 Low SP Supreme Wheat traggono ispirazione dalle classiche scarpe da lavoro e presentano una tomaia in Flax Durabuck con logo Supreme Box sulla parte laterale del tallone").marchio("Nike").modello("Nike Air Force 1").tagliaDisponibile(36).imageUrl("NKAF1LSBrown.png").build());
            repo.save(Scarpa.builder().nome("Nike Air Force 1 Low Supreme bianco").prezzo(149.99d).descrizione("Supreme e Nike rendono omaggio al modello classico made in NYC con questa release delle Nike Air Force 1 Low Supreme bianco. La collaborazione vede l'aggiunta del famoso box logo Supreme sul lato delle tradizionali Air Force 1 nella colorway bianca.").marchio("Nike").modello("Nike Air Force 1").tagliaDisponibile(41).imageUrl("NKAF1LWhite.png").build());
            repo.save(Scarpa.builder().nome("Air Max 1 Travis Scott Cactus Jack Baroque marrone").prezzo(289.99d).descrizione("La collaborazione con l'etichetta discografica di Travis Scott, Cactus Jack, le Nike Air Max 1 Travis Scott Cactus Jack Brown si ispirano alle scarpe da trekking Nike ACG Pocket Knife. Hanno una tomaia in mesh a strati con rivestimenti in Durabuck tono su tono e loghi Swoosh invertiti. ").marchio("Nike").modello("Nike Air Max 1").tagliaDisponibile(39).imageUrl("NKAM1TSCBrown.png").build());
            repo.save(Scarpa.builder().nome("Nike Air DT Max '96 Black White").prezzo(364.99d).descrizione("Con lo stesso design ondulato dell'originale, ispirato ai treni proiettile giapponesi, è pensata per spingere il tuo stile a tutta velocità. Grazie alla rivoluzionaria unità Nike Air a tutta lunghezza che ha messo sottosopra il mondo del running e all'aggiunta di colori nuovi e dettagli frizzanti.").marchio("Nike").modello("Nike Air DT Max").tagliaDisponibile(36).imageUrl("NKADTM96.png").build());
            repo.save(Scarpa.builder().nome("Nike Air Max Dn tutta la notte").prezzo(149.99d).descrizione(" Air Max Dn integra la nostra unità Dynamic Air con sistema di tubi a doppia pressione, per offrire reattività a ogni passo. Il risultato è un design futuristico  e comodo").marchio("Nike").modello("Nike Air Max DN").tagliaDisponibile(41).imageUrl("NKAMDN.png").build());
            repo.save(Scarpa.builder().nome("Nike Dunk Low Veneer").prezzo(109.99d).descrizione("Le Nike Dunk Low Veneer sono state droppate nella variante delle origini. La tomaia è in pregiata pelle scamosciata nei toni del marrone, verde e viola, per un fascino nostalgico ideale per coloro che si fossero persi l'uscita nel 2001.").marchio("Nike").modello("Nike Dunk Low").tagliaDisponibile(36).imageUrl("NKDLV.png").build());
            repo.save(Scarpa.builder().nome("Nike Dunk Low marrone chiaro").prezzo(114.99d).descrizione("Creata per il parquet, ma ideale per la città, torna l'icona del basket degli anni Ottanta con strati esterni perfettamente lucidati e colori classici della squadra. Con un iconico design da basket, Nike Dunk Low.").marchio("Nike").modello("Nike Dunk Low").tagliaDisponibile(40).imageUrl("NKDLBrown.png").build());
            repo.save(Scarpa.builder().nome("Nike Dunk Low Sashiko blu industriale").prezzo(114.99d).descrizione("Le Nikes Dunk Low Industrial Blue Sashiko sono realizzate con tomaia in denim che presenta cuciture bianche a contrasto sui pannelli in denim blu. Le tradizionali cuciture giapponesi Sashiko sono cucite sulla punta e sull'aletta del tallone. ").marchio("Nike").modello("Nike Dunk Low").tagliaDisponibile(41).imageUrl("NKDLSBlue.png").build());
            repo.save(Scarpa.builder().nome("Puma LaMelo Ball MB.03").prezzo(109.99d).descrizione("Le Puma LaMelo Ball MB.03 Toxic combinano stile e funzionalità, ispirandosi a un mondo extraterrestre. Il design integra elementi come melma e artigli, creando un'estetica visivamente aggressiva.").marchio("Puma").modello("Puma MB").tagliaDisponibile(44).imageUrl("PMMB03.png").build());
            repo.save(Scarpa.builder().nome("Puma Palermo ").prezzo(89.99d).descrizione("Direttamente dagli archivi, la PUMA Palermo. Il suo design si basa sul patrimonio calcistico di PUMA e al tempo stesso si rivolge agli appassionati di sneakers ").marchio("Puma").modello("Puma Palermo").tagliaDisponibile(36).imageUrl("PMP.png").build());
            repo.save(Scarpa.builder().nome("Puma rs-X efekt ").prezzo(84.99d).descrizione("La Smash ispirata al mondo del tennis è tornata più in forma che mai, con il suo classico design di linee pulite e allungate, e con collo imbottito e soletta interna aggiornata.").marchio("Puma").modello("Puma RS-X").tagliaDisponibile(43).imageUrl("PMRSX.png").build());
            repo.save(Scarpa.builder().nome("Puma slip stream").prezzo(59.99d).descrizione("Nel 1987, la PUMA Slipstream è entrata in scena come una sneaker da basket, una dichiarazione di stile pronta a sferrare schiacciate funamboliche. Ora è tornata, più bella che mai.").marchio("Puma").modello("Puma slip").tagliaDisponibile(37).imageUrl("PMSS.png").build());
            repo.save(Scarpa.builder().nome("Puma suede XL").prezzo(99.99d).descrizione("Questa rivisitazione del classico modello Suede trae ispirazione dall’eredità di PUMA nel mondo della breakdance e dalla sua influenza sullo streetwear contemporaneo.").marchio("Puma").modello("Puma suede").tagliaDisponibile(36).imageUrl("PMSXL.png").build());
            repo.save(Scarpa.builder().nome("Puma scoot zeros").prezzo(109.99d).descrizione("spirata allo stile veloce e dirompente di Scoot Henderson, questa scarpa riprende gli elementi di design del nostro marchio Hoops Jaws, con un rivestimento in gomma a forma di mascella sulla suola che rappresenta la ferocia e la tenacia di Scoot in campo.").marchio("Puma").modello("Puma scoot zeros").tagliaDisponibile(44).imageUrl("PMSZ.png").build());
            repo.save(Scarpa.builder().nome("Puma exotek ").prezzo(109.99d).descrizione("Il design leggendario e intramontabile delle ST Runner è stato aggiornato: le piccole modifiche alla tomaia e il clip sul tallone fanno soffiare una ventata d’aria fresca").marchio("Puma").modello("Puma exotek ").tagliaDisponibile(36).imageUrl("PME.png").build());
            repo.save(Scarpa.builder().nome("Puma easy rider").prezzo(99.99d).descrizione("Rompi gli schemi con un design unico nel suo genere. La nostra Cassia veste una linea femminile all’avanguardia con una base in rete e pannelli in pelle leggermente oversize").marchio("Puma").modello("Puma easy rider").tagliaDisponibile(39).imageUrl("PMER.png").build());
            repo.save(Scarpa.builder().nome("Asics ex89").prezzo(64.99d).descrizione("La sneaker EX89 combina il look tradizionale della scarpa da basket GEL-EXTREME del 1989 con le più moderne proprietà di ammortizzazione grazie alla tecnologia FF BLAST.").marchio("Asics").modello("asics ex89 ").tagliaDisponibile(43).imageUrl("AC89.png").build());
            repo.save(Scarpa.builder().nome("Asics gel-quantum VIII").prezzo(179.99d).descrizione("La sneaker GEL-QUANTUM 360 VIII  è stata ripensata con dettagli stampati in 5D che ricordano le forme più ergonomiche della natura. Inoltre, l'avanzata tecnologia TRUSSTIC e il contrafforte esterno aiutano a garantire una maggiore stabilità e un look più dinamico.").marchio("Asics").modello("asics gel-quantum").tagliaDisponibile(40).imageUrl("ACGQ8.png").build());
            repo.save(Scarpa.builder().nome("Asics gel-quantum VII").prezzo(119.99d).descrizione("Il concetto di ammortizzazione passa al livello successivo grazie alla sneaker GEL-QUANTUM 360 VII. Le nuove sfumature di colore ispirate alla tradizione giapponese e sfumature rigeneranti che infondono positività. La tecnologia GEL di questa scarpa è progettata per garantire un migliore assorbimento degli urti sotto il piede.").marchio("Asics").modello("asics gel-quantum").tagliaDisponibile(36).imageUrl("ACGQ7.png").build());
            repo.save(Scarpa.builder().nome("Asics japan s").prezzo(54.99d).descrizione("Le scarpe JAPAN S si ispirano a un nostro modello rétro del 1981. Questa versione rielaborata è realizzata con un profilo basso, completato con una punta ispirata ai campi da gioco e colorazioni rétro. ").marchio("Asics").modello("Asics japan").tagliaDisponibile(43).imageUrl("ACJS.png").build());
            repo.save(Scarpa.builder().nome("Asics gel-1130").prezzo(99.99d).descrizione("Le ASICS Gel-1130 sono sneakers dal design ispirato alle Gel-KAYANO 14, con un look simile e una tecnologia aggiornata. ").marchio("Asics").modello("Asics gel").tagliaDisponibile(36).imageUrl("ACG1130.png").build());
            repo.save(Scarpa.builder().nome("Asics gel-Sonoma").prezzo(79.99d).descrizione("La GEL-SONOMA è stata progettata per l'utilizzo outdoor. È progettata con una membrana in GORE-TEX che contribuisce a mantenere i piedi caldi e asciutti quando corri all'aperto.").marchio("Asics").modello("Asics gel").tagliaDisponibile(43).imageUrl("ACGS.png").build());
            repo.save(Scarpa.builder().nome("Asics gel-venture 6").prezzo(49.99d).descrizione("La scarpa da trail running GEL-VENTURE 6 è stata modificata per il moderno esploratore urbano. I suoi materiali tradizionali sono stati riprogettati per passare dagli spazi aperti alle strade cittadine. La tomaia è realizzata a strati con inserti in pelle sintetica per creare un look moderno.").marchio("Asics").modello("Asics gel").tagliaDisponibile(40).imageUrl("ACGV6.png").build());
            repo.save(Scarpa.builder().nome("Asics gel-nyc").prezzo(129.99d).descrizione("Le ASICS Gel-NYC sono caratterizzate da una combinazione di colori grigio ostrica che trasuda uno stile moderno. Il design è completato dalla rinomata tecnologia di ammortizzazione Gel di ASICS, che offre un comfort e un'ammortizzazione superiori.").marchio("Asics").modello("Asics gel").tagliaDisponibile(36).imageUrl("ACGN.png").build());
            repo.save(Scarpa.builder().nome("Reebok atr chill ").prezzo(54.99d).descrizione("Il design della tomaia di queste sneakers ATR Chill si ispira alla tradizione Above the Rim di Reebok, che affonda le sue radici nel mondo del basket. Il comodo sottopiede dona comfort a ogni passo.").marchio("Reebok").modello("Reebok atr").tagliaDisponibile(43).imageUrl("RBAC.png").build());
            repo.save(Scarpa.builder().nome("Reebok classic Leather").prezzo(54.99d).descrizione("Aggiungi una nota diversa ai tuoi look con queste sneakers Reebok. Il modello rivisita le iconiche Classic Leather con dettagli innovativi come i loghi sulla linguetta e il design a inserti, mentre la tomaia rivestita in pelle e nabuk rende la scarpa versatile e confortevole. ").marchio("Reebok").modello("Reebok classic").tagliaDisponibile(44).imageUrl("RBCL.png").build());
            repo.save(Scarpa.builder().nome("Reebok Classic leather ripple").prezzo(59.99d).descrizione("Aggiungi una nota diversa ai tuoi look con queste sneakers Reebok. Il modello rivisita le iconiche Classic Leather con dettagli innovativi come i loghi sulla linguetta e il design a inserti, mentre la tomaia rivestita in pelle e nabuk rende la scarpa versatile e confortevole. ").marchio("Reebok").modello("Reebok Classic").tagliaDisponibile(38).imageUrl("RBCLR.png").build());
            repo.save(Scarpa.builder().nome("Reebok premier road").prezzo(49.99d).descrizione("Preparati a immergerti nel fermento della città con le Reebok Premier Road Plus VI. Queste calzature da donna presentano una tomaia in tessuto con sovrapposizioni in materiale sintetico, che creano linee sinuose e fluide.").marchio("Reebok").modello("Reebok premier").tagliaDisponibile(41).imageUrl("RBPR.png").build());
            repo.save(Scarpa.builder().nome("Reebok Classic sp vegan ").prezzo(49.99d).descrizione("Se i piani cambiano, perché cambiare anche le scarpe? Con le Classic Leather SP Vegan avrai sempre un look perfetto per ogni occasione. Rivisitazione di un classico intramontabile Reebok,").marchio("Reebok").modello("Reebok Classic").tagliaDisponibile(36).imageUrl("RBCSPV.png").build());
            repo.save(Scarpa.builder().nome("Reebok club c mid").prezzo(99.99d).descrizione("Un design fresco, minimalista e al tempo stesso ricco caratterizza le sneakers Club C Mid II Vintage di Reebok. La tomaia in pelle morbida e liscia avvolge comodamente il piede, disegnando un look discreto, caratterizzato da loghi vintage.").marchio("Reebok").modello("Reebok club").tagliaDisponibile(37).imageUrl("RBCM.png").build());
            repo.save(Scarpa.builder().nome("Reebok lt court").prezzo(59.99d).descrizione("Le sneakers LT Court si ispirano ai modelli d'archivio di Reebok. La tomaia in pelle dalle linee essenziali presenta inserti in suede e in TPU di ispirazione rétro, mentre la fodera in spugna garantisce il massimo comfort.").marchio("Reebok").modello("Reebok lt court ").tagliaDisponibile(36).imageUrl("RBIC.png").build());
            System.out.println("✅ Database popolato con successo!");
        } else {
            System.out.println("ℹ️ Database già popolato, salto il caricamento.");
        }
    }
}
